apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    name: api-pod
spec:
  containers:
  - name: api
    image: lucj/messages:1.0
    env:
    - name: MONGODB_URL
      valueFrom:
        secretKeref:
          name: mongo
          key: mongo_url