apiVersion: v1
kind: Pod
metadata:
  name: mongo
  
spec:
  containers:
  - image: mongo:3.6
    name: mongo
    volumeMounts:
      - mountPath: /data/db
        name: data
  volumes:
  - name: data
    gcePersistentDisk:
      pdName: DISK_NAME
      fstype: ext4